
SET  SQL_SAFE_UPDATES = 0;

-- ASEGURAR QUE SE USA LA BASE DE DATOS CORRECTA 
USE `ancalayola`;

-- Volcando datos para la tabla ancalayola.productos: ~8 rows (aproximadamente)
DELETE FROM `productos`;

  /*!40000 ALTER TABLE `productos` DISABLE KEYS */;

INSERT INTO
  productos (
    prod_codigo,
    prod_nombre,
    prod_categoria,
    prod_precio,
    prod_presentacion,
    prod_ingrediente1,
    prod_ingrediente2,
    prod_ingrediente3,
    prod_status,
    prod_imagen
  ) VALUES  
('hor1lt', 'Horchata Litro', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'AgS'), 45, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'lt') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'horchata-1.png'), 
('hor05lt', 'Horchata 500ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'AgS'), 23, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '500ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'horchata-1-2.png'), 
('jam1lt', 'Jamaica Litro', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'AgS'), 45, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'lt') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'jamaica1.png'), 
('jam05lt', 'Jamaica 500ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'AgS'), 23, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '500ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'jamaica1-2.png'), 
('choco1lt', 'Chocomilk Litro', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'AgS'), 45, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'lt') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'choco1.png'), 
('choco05ml', 'Chocomilk 500ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'AgS'), 23, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '500ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'choco1-2.png'), 
('p-p', 'P-Pollo', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 25, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'pollo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-c', 'P-Pierna', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 25, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'cerdo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-r', 'P-Res', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 30, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'res') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-q', 'P-Queso  ', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 30, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-b', 'P-Bola', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 40, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'bola') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-k', 'P-Camaron', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 40, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'camaron') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-f', 'P-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 25, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-a', 'P-Azucar', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 30, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'azucar') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-pc', 'P-Pollo-Pierna', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 35, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'pollo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'cerdo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-pr', 'P-Pollo-Res', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 0, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'pollo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'res') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'N', ''), 
('p-pq', 'P-Pollo-Queso', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 35, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'pollo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-pb', 'P-Pollo-Bola', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 45, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'pollo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'bola') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-pf', 'P-Pollo-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 35, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'pollo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-pqf', 'P-Pollo-Queso-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 40, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'pollo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , 'A', ''), 
('p-cq', 'P-Pierna-Queso', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 30, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'cerdo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-cb', 'P-Pierna-Bola', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 50, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'cerdo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'bola') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-cf', 'P-Pierna-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 30, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'cerdo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-cqf', 'P-Pierna-Queso-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 40, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'cerdo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , 'A', ''), 
('p-cbf', 'P-Pierna-Bola-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 45, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'cerdo') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'bola') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , 'A', ''), 
('p-rq', 'P-Res-Queso', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 40, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'res') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-rb', 'P-Res-Bola', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 45, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'res') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'bola') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-rf ', 'P-Res-Frijol ', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 35, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'res') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-rqf', 'P-Res-Queso-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 45, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'res') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , 'A', ''), 
('p-rbf', 'P-Res-Bola-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 50, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'res') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'bola') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , 'A', ''), 
('p-qb', 'P-3 Quesos', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 45, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'bola') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-qk', 'P-Queso-Camaron', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 50, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'camaron') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-qf', 'P-Queso-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 30, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-qkf', 'P-Queso-Camaron-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 55, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'queso') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'camaron') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , 'A', ''), 
('p-bk', 'P-Bola-Camaron', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 60, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'bola') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'camaron') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-bf', 'P-Bola-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 45, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'bola') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('p-bkf', 'P-Bola-Camaron-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 60, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'bola') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'camaron') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , 'A', ''), 
('p-kf', 'P-Camaron-Frijol', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'P'), 45, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'camaron') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'frijol') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('cc-coca06', 'Coca-Cola 600ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'coca'), 20, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '600ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'cocacola.jpg'), 
('cc-light06', 'Coca Light 600ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'coca'), 20, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '600ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'Coca-Cola_Light.png'), 
('cc-zero06', 'Coca Sin Azucar 600ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'coca'), 20, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '600ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'coca-cola-zero.png'), 
('cc-lata035', 'Coca Lata 355ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'coca'), 15, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '355ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'coca-cola-lata-355.png'), 
('cc-vidrio023', 'Coca Botellita 233ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'coca'), 10, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '233ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'coca-cola-botellita.png'), 
('cc-fam3', 'Coca 3Lt', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'coca'), 50, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '3Lt') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'Coca-cola-3lt.png'), 
('r-fannar06', 'Fanta Naranja 600ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'ORefr'), 20, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '600ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'fanta-naranja.jpg'), 
('r-fanfre06', 'Fanta Fresa 600ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'ORefr'), 20, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '600ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'fanta-fresa.png'), 
('r-sen06', 'Sensao 600ml', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'ORefr'), 20, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = '600ml') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', 'senzao.png'), 
('E-Zah', 'Zanahoria', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'extra'), 10, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', ''), 
('E-Tre', 'Trenza Nutella', (SELECT cat_id FROM categorias WHERE cat_status = 'A' AND cat_codigo = 'extra'), 15, (SELECT presentacion_id FROM presentacion WHERE presentacion_status = 'A' AND presentacion_codigo = 'und') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , (SELECT ingred_id FROM ingredientes WHERE ingred_status = 'A' AND ingred_codigo = 'indef') , 'A', '');


SET SQL_SAFE_UPDATES = 1;
