# script para actualizar los precios y los estados de los productos de la tabla PRODUCTOS

USE `ancalayola`;

UPDATE productos SET prod_precio = 50, prod_status = 'A' WHERE prod_codigo = 'hor1lt';
UPDATE productos SET prod_precio = 25, prod_status = 'A' WHERE prod_codigo = 'hor05lt';
UPDATE productos SET prod_precio = 50, prod_status = 'A' WHERE prod_codigo = 'jam1lt';
UPDATE productos SET prod_precio = 25, prod_status = 'A' WHERE prod_codigo = 'jam05lt';
UPDATE productos SET prod_precio = 50, prod_status = 'A' WHERE prod_codigo = 'choco1lt';
UPDATE productos SET prod_precio = 25, prod_status = 'A' WHERE prod_codigo = 'choco05ml';
UPDATE productos SET prod_precio = 28, prod_status = 'A' WHERE prod_codigo = 'p-p';
UPDATE productos SET prod_precio = 28, prod_status = 'A' WHERE prod_codigo = 'p-c';
UPDATE productos SET prod_precio = 32, prod_status = 'A' WHERE prod_codigo = 'p-r';
UPDATE productos SET prod_precio = 32, prod_status = 'A' WHERE prod_codigo = 'p-q';
UPDATE productos SET prod_precio = 45, prod_status = 'A' WHERE prod_codigo = 'p-b';
UPDATE productos SET prod_precio = 45, prod_status = 'A' WHERE prod_codigo = 'p-k';
UPDATE productos SET prod_precio = 28, prod_status = 'A' WHERE prod_codigo = 'p-f';
UPDATE productos SET prod_precio = 32, prod_status = 'A' WHERE prod_codigo = 'p-a';
UPDATE productos SET prod_precio = 37, prod_status = 'A' WHERE prod_codigo = 'p-pc';
UPDATE productos SET prod_precio = 0, prod_status = 'N' WHERE prod_codigo = 'p-pr';
UPDATE productos SET prod_precio = 37, prod_status = 'A' WHERE prod_codigo = 'p-pq';
UPDATE productos SET prod_precio = 48, prod_status = 'A' WHERE prod_codigo = 'p-pb';
UPDATE productos SET prod_precio = 37, prod_status = 'A' WHERE prod_codigo = 'p-pf';
UPDATE productos SET prod_precio = 45, prod_status = 'A' WHERE prod_codigo = 'p-pqf';
UPDATE productos SET prod_precio = 32, prod_status = 'A' WHERE prod_codigo = 'p-cq';
UPDATE productos SET prod_precio = 55, prod_status = 'A' WHERE prod_codigo = 'p-cb';
UPDATE productos SET prod_precio = 32, prod_status = 'A' WHERE prod_codigo = 'p-cf';
UPDATE productos SET prod_precio = 45, prod_status = 'A' WHERE prod_codigo = 'p-cqf';
UPDATE productos SET prod_precio = 48, prod_status = 'A' WHERE prod_codigo = 'p-cbf';
UPDATE productos SET prod_precio = 45, prod_status = 'A' WHERE prod_codigo = 'p-rq';
UPDATE productos SET prod_precio = 48, prod_status = 'A' WHERE prod_codigo = 'p-rb';
UPDATE productos SET prod_precio = 37, prod_status = 'A' WHERE prod_codigo = 'p-rf ';
UPDATE productos SET prod_precio = 48, prod_status = 'A' WHERE prod_codigo = 'p-rqf';
UPDATE productos SET prod_precio = 55, prod_status = 'A' WHERE prod_codigo = 'p-rbf';
UPDATE productos SET prod_precio = 48, prod_status = 'A' WHERE prod_codigo = 'p-qb';
UPDATE productos SET prod_precio = 55, prod_status = 'A' WHERE prod_codigo = 'p-qk';
UPDATE productos SET prod_precio = 32, prod_status = 'A' WHERE prod_codigo = 'p-qf';
UPDATE productos SET prod_precio = 60, prod_status = 'A' WHERE prod_codigo = 'p-qkf';
UPDATE productos SET prod_precio = 63, prod_status = 'A' WHERE prod_codigo = 'p-bk';
UPDATE productos SET prod_precio = 48, prod_status = 'A' WHERE prod_codigo = 'p-bf';
UPDATE productos SET prod_precio = 65, prod_status = 'A' WHERE prod_codigo = 'p-bkf';
UPDATE productos SET prod_precio = 48, prod_status = 'A' WHERE prod_codigo = 'p-kf';
UPDATE productos SET prod_precio = 20, prod_status = 'A' WHERE prod_codigo = 'cc-coca06';
UPDATE productos SET prod_precio = 20, prod_status = 'A' WHERE prod_codigo = 'cc-light06';
UPDATE productos SET prod_precio = 20, prod_status = 'A' WHERE prod_codigo = 'cc-zero06';
UPDATE productos SET prod_precio = 15, prod_status = 'N' WHERE prod_codigo = 'cc-lata035';
UPDATE productos SET prod_precio = 10, prod_status = 'N' WHERE prod_codigo = 'cc-vidrio023';
UPDATE productos SET prod_precio = 55, prod_status = 'A' WHERE prod_codigo = 'cc-fam3';
UPDATE productos SET prod_precio = 20, prod_status = 'N' WHERE prod_codigo = 'r-fannar06';
UPDATE productos SET prod_precio = 20, prod_status = 'N' WHERE prod_codigo = 'r-fanfre06';
UPDATE productos SET prod_precio = 20, prod_status = 'N' WHERE prod_codigo = 'r-sen06';
UPDATE productos SET prod_precio = 10, prod_status = 'A' WHERE prod_codigo = 'E-Zah';
UPDATE productos SET prod_precio = 15, prod_status = 'N' WHERE prod_codigo = 'E-Tre';
